### ISSUE TITLE
webstation custom nginx 

### ISSUE THREAD

**Issue by xavave** [marknokes/synology-nginx-config#1]
thank you for your contribution about synology nginx :)

this not an issue, just a question: and I wrote the same comment on https://manthings.net/custom-nginx-config-for-synology-web-station-on-dsm-7-2/#comment-175 but I can't see my comment posted (maybe waiting for validation)

- what are the difference between your command to restart nginx and "synosystemctl restart nginx" ?

- I use nginx proxy manager (aka n.p.m.) on my synology docker so I have redirected all traffic from my router (ports 80 and 443) to the synology nginx proxy manager ports. It works fine but, I have a wordpress site hosted in webstation.
As webstation still use its own nginx on ports 80/443 my wordpress site url returns now a 404
Should I try to write a kind of ip table rule to force redirect to 80/443  instead of custom npm ports just when origin referrer  is my wordpress website url (which is e.g. [mywordpresssite.mydomain.fr](http://mywordpresssite.mydomain.fr/)) (so my website won't use npm and still would use webstation nginx)
- Or, should I try to force webstation to use nginx from npm by changing webstation config file?

What are your thoughts about this please?

**Comment by marknokes** [comment]
Hi Xavier! Yep, the spam filter on my site blocked your comment, but I just approved it. I'll provide my thoughts there and there :)

I believe the differences between `synosystemctl restart nginx` and `nginx -s reload && nginx -t` are that the first one is Synology's abstraction of the second. Also, the second one does a test of the config file to ensure it doesn't have any syntax errors and immediately prints the output of the test.

For your wordpress site, I don't have experience with nginx proxy manager, but can you set up a reverse proxy using the native Synology Application Portal (Control Panel > Application Portal > Reverse Proxy) to see if it would intercept the traffic? Then you could set custom ports in webstation for that site and have the reverse proxy rule point to it. I'm just taking a wild guess :) I hope something here helps get you closer!

**Comment by xavave** [comment]
Thank you Mark,

I know about the synology integrated reverse proxy but I wanted to use basic authentication realm and this is not implemented in synology version (you can just add a control accesss list by ip/range). NPM is more sofisticated and you can use different options for auth

npm interface
![image](https://github.com/marknokes/synology-nginx-config/assets/3501675/8d6f9ac5-65c5-4f72-a8ed-69ee97bccb7f)

npm auth option
![image](https://github.com/marknokes/synology-nginx-config/assets/3501675/6bb8d311-ef4b-4f39-b200-79f10039e90a)

basic auth form automatically added (optional) before connecting to a hosted docker container
![image](https://github.com/marknokes/synology-nginx-config/assets/3501675/501966aa-7685-4dfd-bead-1a5c9f3b6e08)

You maybe know where is the conf file for webstation telling "I want to use niginx, or apache" --> I could update it to redirect to my npm, but I don't know where this conf file can be...

**Comment by marknokes** [comment]
To switch between apache and nginx you can do it from the Web Station UI. Navigate to Web Service and open the service for your website. From there you would change the option for `HTTP back-end-server`. I'm not sure about the config file location, though.
